customhost = "database-1.ch5nkldebuc6.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "limyijian-employee"
customregion = "us-east-1"
